### ISSUE TITLE
The function of nvalloc_malloc_to()

### ISSUE THREAD

**Issue by saltway** [ISCS-ZJU/NVAlloc#2]
hi,
I have read your interesting paper, but I find it hard to implement the function of  _nvalloc_malloc_to(size_t size, void **ptr)_.
This function can provide a failure-atomic process of allocation and linking.
But in real implementation, for example, in FP-tree, the node allocated needs to be modified first (shifting entries to this new node) and then linked to (referenced by) its left sibling. It seems that a single function like _nvalloc_malloc_to(size_t size, void **ptr)_ is not sufficient. If a crash takes place while shifting entries (assuming entry shifting begins after _nvalloc_malloc_to()_ ), the status of this new node is actually the same as leaked.
How to handle this problem or would you please introduce the implementation of your experiments on FP-tree?

**Comment by dangzzz** [comment]
Your issue can be solved by adding a callback function to nvalloc_malloc_to(), which completes the node modification process before the allocator persistently allocate the node and link it to the sibling.  See _constructor function_ at https://pmem.io/pmdk/manpages/linux/master/libpmemobj/pmemobj_alloc.3/.

**Comment by saltway** [comment]
I'm sorry I can't catch you clearly. The URL seems irrelevant to nvalloc_malloc_to(). Maybe you mean the implementation of nvalloc_malloc_to() in your source code.  I truncate parts of the code and list them as follows: ( sorry for my shallow operation ) 

cache->ncached[now]--;
add_minilog(minilog, &global_index, ptr);
**_meta_set(cache->avail[now][cache->ncached[now]].metas, cache->avail[now][cache->ncached[now]].index);_**
_**_mm_clwb(cache->avail[now][cache->ncached[now]].metas);**_
 _mm_sfence();
 if (cache->ncached[now] == 0)
 {
      cache->bm = cache_bitmap_flip(cache->bm, now);
 }
cache->now = now;
ret = cache->avail[now][cache->ncached[now]].ret;
 *ptr = ret;
 _mm_clwb(ptr);
_mm_sfence();
return ret;

Do you mean the node modification process should occur between _meta_set() and _mm_clwb()? The mini log seems not sufficient for handling memory leaks. (indeed, my thought is constrained by the two-phase strategy implemented by PMDK and nv-malloc)

**Comment by dangzzz** [comment]
The node modification process is placed before add_minilog (line 2 in the code you listed). At that time, NVAlloc allocated the memory block volatilely and did not write any persistent data to PM (and also didn't link the node to the sibling). If a power failure happens in the node modification process, the memory block is still treated as available after recovery and can be allocated again. There may be junk data in the block, but no memory leak occurs.

In fact, this method has the same execution logic as the two-phase strategy implemented in nvm_malloc. The only difference is that the former integrates the three functions of the latter into one function. Of course, you can use the two-phase strategy by splitting the nvalloc_malloc_to() into two parts, the first to allocate a memory block volatilely and the second to persist the allocation and link in the pointer. Then you can place the node modification process between the two functions.

PS: No code should be placed between _meta_set() and _mm_clwb(), since the processor may implicitly flush the data before _mm_clwb() is executed. You can't tell whose execution result is persisted first, newly added code or meta_set().

Hope this helps.

**Comment by saltway** [comment]
Thanks for your rapid and patient response.  (Sorry for my new dumb questions)
But I'm still confused about the minilog.  How can it keep allocation and linking in a failure-atomic transaction? Following the indication of the ptr recorded in the minilog,  no information for recovering can be found (in my own effort). Maybe I miss some critical information.
One another strange question: in the implementation of nvm_activate() in nv_malloc, the status transitions are interleaved with the linking operation by embedding sfence. Only one persist operation is applied for the status transitions in the end.  As far as I know, sfence will not force the persist (or writeback) order of different cache lines (status transition and linking are operated on different cache lines) and the status may be STATE_PREACTIVATE while the linking operation is persisted.  Under this scenario, the node may be allocated again (this is much worse than leaked!). Maybe I miss some critical information again.

**Comment by dangzzz** [comment]
The _ptr_ (a double-pointer, void **) recorded in the mini-log points to where the pointer is linked. The pointer linking is executed before _\_meta_set()_. In recovery, if the value of _ptr_ is NULL, the __meta_set()_ is not executed.  If the value of _ptr_ is not NULL,  the _\_meta_set()_  of the same memory block can be re-executed with the help of the pointer (which points to the memory block) stored in _\*ptr_.

I'm not particularly familiar with the code of nvm_malloc, you should ask the author of nvm_malloc for a definitive answer. In my mind,  nvm_malloc will redo all the allocations recorded in its circular write-ahead log at the time of recovery.  The failed allocation is guaranteed to be re-executed and thus the order of persistence doesn't matter. The nvm_malloc only needs to ensure the information of an allocation is persisted before its corresponding record in the circular log is overwritten.

**Comment by saltway** [comment]
I guess "the value of ptr" means the value of ptr stored in the log entry. This value is the address on which the address of the newly allocated node/space will be stored. Following the logic mentioned in your description, the code execution order may be 

constructing the new node -> add_minilog()->linking ->_meta_set(). 
(processing linking before add_minilog() is dangerous as this new node may be allocated again)

 If the value of ptr is not NULL (I think, this means add_minilog() has finished), it seems hard to distinguish the status left by failure, for that failure may take place just before linking or _meta_set(). The pointer stored in *ptr (or the pointer stored on ptr) may refer to one of the three kinds of nodes:

_new node I_ (linked but not persistently allocated ) 
_new node II_ (persistently allocated ) 
_original sibling node_ (linking is not performed)

 Maybe we need a function to check whether this node is allocated or not, and thus the _new node I_ and the _original sibling node_ (or _new node II_) can be distinguished.  This solution may incur extra overhead in traversing the logs. (maybe it's just the part that I missed before in your design)

Indeed, my problem is how to "re-executed with the help of the pointer (which points to the memory block) stored in *ptr". And maybe I also miss some information on how to get "the same memory block", e.g. will the allocation always return the same block if _meta_set() is not invoked? (this seems strange if multiple threads work together)

**Comment by dangzzz** [comment]
I'm sorry I didn't describe it clearly.  I mistyped "the value of *ptr"  as "the value of ptr". This value is the address of the newly allocated node. 

The code execution order that you list is correct. Maybe the following example code can help to understand (I don't include the things about constructing in this example).

```
struct Node {
  size_t data;
  struct Node * next;
}

struct Node * old_node;
... ...
struct Node * new_node = nvalloc_malloc_to(sizeof(struct Node), &old_node->next);

//After the execution of add_minilog(), the value of ptr stored in the log entry is &old_node->next.
//After the execution of linking, *ptr is new_node (i.e., (uintptr_t)*ptr == (uintptr_t)new_node == (uintptr_t)old_node->next).

... ...

//In recovery

for(each log_entry in minilog){
  struct Node ** ptr = get_ptr_from_log_entry(log_entry);
//ptr == &old_node->next
  if(*ptr != NULL){
    _meta_set(get_meta_address_from_block_address(*ptr));
  } else{
    continue;
  }
}

//After recovery, you can allocate or free memory blocks.
... ...


```
If the value of *ptr is NULL, both linking and _meta_set() are not executed, it is consistent and we don't need to do anything.

If the value of *ptr is not NULL (*ptr != NULL), it means _linking_ has finished. We need to ensure _meta_set() also be finished.

how to finish _meta_set() ("re-executed with the help of *ptr")?

To re-execute _meta_set() for the new_node, we need to know the address of its metadata. Since we already have the starting address of the new_node (i.e., *ptr), we can easily get its metadata address just like what we do when freeing it. 

"Will the allocation always return the same block if _meta_set() is not invoked" What we do here is not to allocate a new memory block, but to locate and modify the metadata of the previous memory block.

**Comment by saltway** [comment]
I add something into your example:

... ...
old_node->next = old_sibling; // NULL only if the old_node is the rightmost one
... ...
//After the execution of add_minilog(), the value of ptr stored in the log entry is &old_node->next.
//Before the execution of linking, *ptr is _old_node->next_ (old_sibling)
//After the execution of linking, *ptr is new_node

Maybe the analysis under the example can be updated as:

If the value of *ptr is NULL, this node is the rightmost node while both linking and _meta_set() are not executed, it is consistent and we don't need to do anything.

If the value of *ptr is not NULL (*ptr != NULL), the status is uncertain and we ... ...
... ...
 

It seems that we still need a function to check whether *ptr is allocated or not (just try to save some store and flush instructions). I guess your method may be to overwrite the metadata (mark *ptr as allocated on the metadata) without considering whether *ptr is allocated or not.

**Comment by dangzzz** [comment]
I see what you mean. You are correct. If *ptr is not NULL before nvalloc_malloc_to() is called, overwriting the metadata without checking whether *ptr is pointing to the new block is dangerous. I should use a better implementation of WAL to replace the mini-log. Thanks for pointing that out!

**Comment by saltway** [comment]
Thank you so much for this delightful conversation.
